// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCih_nXkEBtM9ThHrXqC2iCpSIlbSur6hQ',
    appId: '1:980173563615:web:3d15ef4ba45aa1555b6b6a',
    messagingSenderId: '980173563615',
    projectId: 'restaurant-280d3',
    authDomain: 'restaurant-280d3.firebaseapp.com',
    storageBucket: 'restaurant-280d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-5CHDHKXvIsVIzWSEmYTVcQDVGj29Dlo',
    appId: '1:980173563615:android:4a5ae38c0f8bc3eb5b6b6a',
    messagingSenderId: '980173563615',
    projectId: 'restaurant-280d3',
    storageBucket: 'restaurant-280d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwkKbJyoelYc0-0CFa0fcdyITWakJ6dwY',
    appId: '1:980173563615:ios:52e141d2f5fb115c5b6b6a',
    messagingSenderId: '980173563615',
    projectId: 'restaurant-280d3',
    storageBucket: 'restaurant-280d3.appspot.com',
    iosBundleId: 'com.example.restaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwkKbJyoelYc0-0CFa0fcdyITWakJ6dwY',
    appId: '1:980173563615:ios:c07a790837bae1165b6b6a',
    messagingSenderId: '980173563615',
    projectId: 'restaurant-280d3',
    storageBucket: 'restaurant-280d3.appspot.com',
    iosBundleId: 'com.example.restaurant.RunnerTests',
  );
}
